apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: limitrange-spring-petclinic-role
  namespace: spring-petclinic
rules:
- apiGroups: [""]
  resources: ["limitranges"]
  verbs: ["create"]
  namespace: spring-petclinic